name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: platane/snk@v3
        with:
          github_user_name: HARSHIT071004
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=orange&color_dots=#e2e8f0,#cbd5e1,#94a3b8,#6366f1,#4f46e5

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: .
          keep_files: true
